[hangman_bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
[hangman_bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/HangMan/Hangman.py", line 687, in hint_callback
    await callback_query.answer(f"Hint: The word contains the letter '{hint}'")
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 159, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 73, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
[hangman_bot] Waiting for 6 seconds before continuing (required by "messages.EditMessage")
[hangman_bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/HangMan/Hangman.py", line 687, in hint_callback
    await callback_query.answer(f"Hint: The word contains the letter '{hint}'")
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 159, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 73, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "/home/ubuntu/HangMan/Hangman.py", line 617, in guess_callback
    await client.edit_message_text(
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 17 seconds is required (caused by "messages.EditMessage")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/HangMan/Hangman.py", line 627, in guess_callback
    await client.edit_message_text(
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
[hangman_bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
Telegram says: [420 FLOOD_WAIT_X] - A wait of 23 seconds is required (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/HangMan/Hangman.py", line 1214, in play_again_callback
    await callback_query.message.edit_text(
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/types/messages_and_media/message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 23 seconds is required (caused by "messages.EditMessage")
Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/HangMan/Hangman.py", line 687, in hint_callback
    await callback_query.answer(f"Hint: The word contains the letter '{hint}'")
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 159, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 73, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/HangMan/Hangman.py", line 687, in hint_callback
    await callback_query.answer(f"Hint: The word contains the letter '{hint}'")
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 159, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 73, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
[hangman_bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
